# Configures the port for the server
server:
  port: 8000

# Configures Spring Boot application properties
spring:
  profiles:
    # Sets the active profile, defaulting to 'local' if not specified
    active: ${ENV:local}
  application:
    name: # Specify the name of your application here
  datasource:
    # Configures the datasource for connecting to MySQL database
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${myServer.mysql}/e-shopping?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: ${myServer.username}
    password: ${myServer.password}
    hikari:
      maximum-pool-size: 4
  jpa:
    # Configures JPA properties
    open-in-view: false
    hibernate:
      ddl-auto: none
      globally_quoted_identifiers: true
      dialect: org.hibernate.dialect.MySQLDialect
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    database: mysql
    show-sql: true # Whether to log SQL statements
    format_sql: true # Whether to format SQL queries
  graphql:
    # Configures GraphQL endpoint path and enables GraphiQL
    path: /graphql
    graphiql:
      enabled: true

# Configures logging properties
logging:
  file:
    name: /var/log/logs_${server.port}/server.log # Specifies the log file location
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15}:%line - %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15}:%line - %msg%n'
  level:
    root: INFO # Sets the root logger level to INFO
