# This file is configuration for local environment

# Configuration for connecting to the MySQL server
myServer:
  mysql: localhost:3306  # MySQL server hostname and port
  username: root
  password: root1234

# Logging configuration
logging:
  level:
    root: info  # Root logger level set to 'info'
    org.hibernate:
      SQL: DEBUG  # Sets logging level for Hibernate SQL statements to 'DEBUG'
      type.descriptor.sql.BasicBinder: TRACE  # Sets logging level for SQL bind parameter values to 'TRACE'

spring:
  jpa:
    hibernate:
      ddl-auto: update
